### PR TITLE
fix missing colons in REST URL

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by daniel-aguilar-garcia** [comment]
Hi Robert. Thanks for your review. Sorry but I don't understand why you add this ':' here.

localhost:52773/:RPLMMG

Can you explain it? Thanks!

**Comment by rcemper** [comment]
it results from your ROUTES in class **dc.Sample.UrlREST**
```
<Routes>
<!-- Server Info -->
<Route Url="/" Method="GET" Call="GetInfo" Cors="true"/>
<!-- Swagger specs -->
<Route Url="/swagger" Method="GET" Call="SwaggerSpec" />
<!-- GET method to return JSON for a given url shortUrl-->
<Route Url="/:shortUrl" Method="GET" Call="GetUrl"/>
<!-- GET method to return JSON for a given url shortUrl-->
<Route Url="/info/:shortUrl" Method="GET" Call="GetUrlInfo"/>
<!-- Delete a url with id-->
<Route Url="/:id" Method="DELETE" Call="DeleteUrl"/>
<!-- Create a url-->
<Route Url="/" Method="POST" Call="CreateUrl"/>
<!-- GET method to return JSON for a given url id-->
<Route Url="/delete/:id" Method="GET" Call="DeleteUrl"/>
</Routes>
```
if I use the colons as described here it works
if I omit it, then it fails  because localhost:52773/RPLMMG   doesn't exist

**Comment by daniel-aguilar-garcia** [comment]
Hi Robert, thanks again for your answer.

I wrote this:

<Route Url="/:shortUrl" Method="GET" Call="GetUrl"/>

Because I thought that writing the colon ':shortUrl'  was the way to pass 'shortUrl' like parameter to the method 'GetUrl'

//Definition of method GetUrl
ClassMethod GetUrl(shortUrl As %String) As %Status
...

Is not correct?

It works in my machine without adding the colon in the url. 

Did you see the demo's video? Doesn't work you like it does for me?

https://youtu.be/tHRrW5JqNMA

**Comment by rcemper** [comment]
I just can say that it didn't work for me without :
just returned "page not found" but worked with :
But I worked from Win into Docker Desktop.

that was my finding
I saw the video and have no explanation for one or the other side.
I have no problem if you just forget the PR.

BTW. giving the REST  service no name but just / might be a reason

Regards, Robert



Am 05.02.2023 um 22:00 schrieb Daniel Aguilar:

**Comment by rcemper** [comment]
I have to excuse.!
It works as described. 
have no explanation.
pls forget the PR

**Pull request closed without merging**
